python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00000
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00001
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00002
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00003
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00004
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00005
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00006
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00007
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00008
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00009
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00010
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00011
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00012
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00013
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00014
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00015
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00016
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00017
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00018
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00019
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00020
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00021
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00022
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00023
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00024
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00025
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00026
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00027
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00028
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00029
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00030
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00031
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00032
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00033
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00034
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00035
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00036
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00037
python ComputeCls.py /home/nicolascs/archaia_image-classification/images/00038