python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00000 /home/nicolascs/archaia_image-classification/artifacts_nobg/00000
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00001 /home/nicolascs/archaia_image-classification/artifacts_nobg/00001
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00002 /home/nicolascs/archaia_image-classification/artifacts_nobg/00002
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00003 /home/nicolascs/archaia_image-classification/artifacts_nobg/00003
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00004 /home/nicolascs/archaia_image-classification/artifacts_nobg/00004 
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00005 /home/nicolascs/archaia_image-classification/artifacts_nobg/00005
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00006 /home/nicolascs/archaia_image-classification/artifacts_nobg/00006
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00007 /home/nicolascs/archaia_image-classification/artifacts_nobg/00007
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00008 /home/nicolascs/archaia_image-classification/artifacts_nobg/00008
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00009 /home/nicolascs/archaia_image-classification/artifacts_nobg/00009
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00010 /home/nicolascs/archaia_image-classification/artifacts_nobg/00010
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00011 /home/nicolascs/archaia_image-classification/artifacts_nobg/00011
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00012 /home/nicolascs/archaia_image-classification/artifacts_nobg/00012
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00013 /home/nicolascs/archaia_image-classification/artifacts_nobg/00013
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00014 /home/nicolascs/archaia_image-classification/artifacts_nobg/00014
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00015 /home/nicolascs/archaia_image-classification/artifacts_nobg/00015
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00016 /home/nicolascs/archaia_image-classification/artifacts_nobg/00016
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00017 /home/nicolascs/archaia_image-classification/artifacts_nobg/00017
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00018 /home/nicolascs/archaia_image-classification/artifacts_nobg/00018
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00019 /home/nicolascs/archaia_image-classification/artifacts_nobg/00019
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00020 /home/nicolascs/archaia_image-classification/artifacts_nobg/00020
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00021 /home/nicolascs/archaia_image-classification/artifacts_nobg/00021
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00022 /home/nicolascs/archaia_image-classification/artifacts_nobg/00022
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00023 /home/nicolascs/archaia_image-classification/artifacts_nobg/00023
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00024 /home/nicolascs/archaia_image-classification/artifacts_nobg/00024
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00025 /home/nicolascs/archaia_image-classification/artifacts_nobg/00025
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00026 /home/nicolascs/archaia_image-classification/artifacts_nobg/00026
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00027 /home/nicolascs/archaia_image-classification/artifacts_nobg/00027
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00028 /home/nicolascs/archaia_image-classification/artifacts_nobg/00028
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00029 /home/nicolascs/archaia_image-classification/artifacts_nobg/00029
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00030 /home/nicolascs/archaia_image-classification/artifacts_nobg/00030
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00031 /home/nicolascs/archaia_image-classification/artifacts_nobg/00031
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00032 /home/nicolascs/archaia_image-classification/artifacts_nobg/00032
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00033 /home/nicolascs/archaia_image-classification/artifacts_nobg/00033
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00034 /home/nicolascs/archaia_image-classification/artifacts_nobg/00034
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00035 /home/nicolascs/archaia_image-classification/artifacts_nobg/00035
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00036 /home/nicolascs/archaia_image-classification/artifacts_nobg/00036
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00037 /home/nicolascs/archaia_image-classification/artifacts_nobg/00037
python test_finetuned_removebg.py /home/nicolascs/archaia_image-classification/filtered_images/00038 /home/nicolascs/archaia_image-classification/artifacts_nobg/00038