python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00000 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00000
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00001 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00001
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00002 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00002
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00003 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00003
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00004 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00004 
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00005 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00005
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00006 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00006
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00008 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00008
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00009 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00009
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00010 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00010
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00011 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00011
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00012 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00012
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00013 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00013
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00014 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00014
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00015 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00015
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00016 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00016
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00017 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00017
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00018 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00018
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00019 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00019
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00020 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00020
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00021 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00021
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00022 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00022
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00023 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00023
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00024 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00024
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00025 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00025
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00026 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00026
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00027 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00027
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00028 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00028
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00029 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00029
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00030 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00030
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00031 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00031
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00032 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00032
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00033 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00033
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00034 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00034
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00035 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00035
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00036 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00036
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00037 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00037
python test_finetuned_removebg.py /home/ncaytuir/data/ArchaIA_Project/dataset_v1/filtered_images/00038 /home/ncaytuir/data/ArchaIA_Project/dataset_v1/nobg_filtered_images/00038